<?php

return [
    'Dhanmondi',
    'Gulshan',
    'Banani',
    'Uttara',
    'Mirpur',
    'Mohammadpur',
    'Badda',
    'Rampura',
    'Khilgaon',
    'Shahbagh',
    'Motijheel',
    'Paltan',
    'Farmgate',
    'Tejgaon',
    'Bashundhara',
    'Baridhara',
    'Aftabnagar',
    'Mohakhali',
    'Jatrabari',
    'Wari',
    'Lalbagh',
    'Old Dhaka',
    'Sutrapur',
    'Shyamoli',
    'Adabor',
    'Kafrul',
    'Cantonment',
    'Mugda',
    'Demra',
    'Khilkhet',
    'Kuril',
    'Puran Dhaka',
];
